// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/337587de8c13868283993bfacdcdd1a0f3291e7f/path-exists/index.d.ts
declare module 'path-exists' {
// Type definitions for path-exists 1.0.0
// Project: https://github.com/sindresorhus/path-exists
// Definitions by: Shogo Iwano <https://github.com/shiwano>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


interface PathExists {
    (path: string, callback: (error: Error, exists: boolean) => void): void;
    sync(path: string): boolean;
}

var pathExists: PathExists;
export = pathExists;
}
